### ISSUE TITLE
SSD1306 OLED screen

### ISSUE THREAD

**Issue by MagdaMa** [matix2120/LoRaNode#3]
obsługa wyświetlacza SSD1306 na Arduino przez SPI

**Comment by kkemot** [comment]
Please prepare first draft of UI on OLED screen.
You can use u8glib library from:
https://github.com/olikraus/U8glib_Arduino

**Comment by kkemot** [comment]
Try to display below parameters on LCD:
- PM2.5 value / level [%[
- PM10 value / level [%]
- pressure value
- temp and humidity
- GPS status(fix status from GPRMC frame)
- UMTC date/time
- LoRa status (connected/disconnected)

If you need more space on LCD you could switch printed screens every 5s (for example: startup screen<version, ... > -> sensor screen<5s> -> radio screen<5s> -> sensor screen<5s> -> etc )
